### ISSUE TITLE
Can't load Kernel binary: Invalid kernel binary format version. No active package pana.

### ISSUE THREAD

**Issue by marandaneto** [axel-op/dart_package_analyzer#12]
Hey, I'm getting this error since today:

> Running pana
>   Can't load Kernel binary: Invalid kernel binary format version.
>   No active package pana.
> Error: Pana exited with code 65

The script is as simple as that:

```
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          relativePath: dart/
      - name: Check scores
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
          if (( $PERCENTAGE < 100 ))
          then
            echo Score too low!
            exit 1
          fi
```

it was working normally, not sure if the ubuntu-latest or something else changed.

PR with the error is here: https://github.com/getsentry/sentry-dart/pull/245/checks?check_run_id=1564311109
