### ISSUE TITLE
Request for workaround for cross-fork reporter issue

### ISSUE THREAD

**Issue by GroovinChip** [axel-op/dart_package_analyzer#16]
As seen in #2, when running this action on cross-fork PR's, the job succeeds but is not able to publish a formatted report due to security issues. As a workaround, perhaps the relevant logs from the job output itself could be captured and published either as a formatted report or a downloadable job artifact?

Filed separately from #2 per request.

**Comment by axel-op** [comment]
Hi @GroovinChip! Sorry for the delay. I've added with 63f970d5cb4e4bf095d6ca6bf6963a74174c4c92 a new output called `json_output` that contains the full JSON report as you wanted. Here's how you can parse it using the `jq` bash command:

```yml
name: Example workflow
on: [push, pull_request]

jobs:

  package-analysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Check scores
        env:
          JSON_OUTPUT: ${{ steps.analysis.outputs.json_output }}
        run: |
          TOTAL_SCORE=$(jq -r '.scores.grantedPoints' <<< "$JSON_OUTPUT")
        # ...
```

Tell me how this works for you 🙂 And feel free to close this issue if this solves it ☺
