### ISSUE TITLE
No report on pull requests from forks

### ISSUE THREAD

**Issue by axel-op** [axel-op/dart_package_analyzer#2]
## Description
When the action is triggered by the `pull_request` event, if the pull request is from a different repository (a fork), the action fails with the error "Resource not accessible by integration".

EDIT: this behavior has changed. See the comment below.

## Why is this happening
This action uses the [`GITHUB_TOKEN`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token) you provide to call the GitHub API and to post the result of its analysis.
As explained [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token), [here](https://github.community/t5/GitHub-Actions/Github-Workflow-not-running-from-pull-request-from-forked/m-p/33547/highlight/true#M1555), or [here](https://github.com/actions/labeler/issues/12), GitHub for now reduces the permissions of this token when the action is triggered by another repository. 
Therefore an error is thrown when this action tries to call the API in this situation.

![Permissions for the GITHUB_TOKEN](https://user-images.githubusercontent.com/49279289/72079867-fcf02c80-32fb-11ea-9625-4ca03991b072.png)

## Current workaround
A possible workaround is to edit your workflow to trigger this action only when pull requests come from the same repository. This can be done by adding an if-condition, as illustrated below:

```yml
name: Example workflow
on: [push, pull_request]

jobs:

  package-analysis:
    if: github.event_name != 'pull_request' || github.actor == '[username]' # Replace [username] by the username of your repo
    runs-on: ubuntu-latest
    steps:
      - ...
```

## 
I will update this issue if there is new information on this.
