### ISSUE TITLE
Unable to resolve actions. Repository not found: axel-op/dart-package-analyzer.

### ISSUE THREAD

**Issue by ebjorklund01** [axel-op/dart_package_analyzer#20]
Running into the error `Unable to resolve actions. Repository not found: axel-op/dart-package-analyzer.`. when trying to run this on pull requests. I have not seen this before and have been using this action in pull requests for some time and are unsure what is causing this issue.

**Actions setup and Code analysis job:**
```
on:
  pull_request:
    branches: [ development, qa ]

name: Test, Build and Release android and iOS apps
defaults:
  run:
    working-directory: ./
jobs:
  package-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: axel-op/dart-package-analyzer@v3
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
```

**Actions log**
```
Current runner version: '2.291.1'
Operating System
Virtual Environment
Virtual Environment Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Error: Unable to resolve actions. Repository not found: axel-op/dart-package-analyzer.
```
