### ISSUE TITLE
fatal: detected dubious ownership in repository at '/github/workspace'

### ISSUE THREAD

**Issue by littleGnAl** [axel-op/dart_package_analyzer#27]
I run into an issue when using the `axel-op/dart-package-analyzer@v3` recently, the error log
```
Running pana
  {"logName":"pana","level":"WARNING","message":"Flutter SDK path was not specified, pana will use the default Dart SDK to run `dart analyze` on Flutter packages."}
  {"logName":"pana","level":"INFO","message":"Running `dart --version`..."}
  {"logName":"pana","level":"INFO","message":"Running `flutter --no-version-check --version --machine`..."}
  {"logName":"pana","level":"INFO","message":"Running `git rev-parse --show-toplevel`..."}
  {"level":"SHOUT","message":"Problem analyzing /github/workspace","error":"Failed to run `rev-parse --show-toplevel`.\nfatal: detected dubious ownership in repository at '/github/workspace'\nTo add an exception for this directory, call:\n\n\tgit config --global --add safe.directory /github/workspace","stackTrace":"#0      runGit (package:pana/src/tool/git_tool.dart:41:5)\n<asynchronous suspension>\n#1      withTempDir (package:pana/src/utils.dart:134:12)\n<asynchronous suspension>\n#2      runGitIsolated (package:pana/src/tool/git_tool.dart:52:10)\n<asynchronous suspension>\n#3      _detectGitRoot (package:pana/src/package_analyzer.dart:274:14)\n<asynchronous suspension>\n#4      PackageAnalyzer.inspectDir.<anonymous closure> (package:pana/src/package_analyzer.dart:95:23)\n<asynchronous suspension>\n#5      withTempDir (package:pana/src/utils.dart:134:12)\n<asynchronous suspension>\n#6      main (file:///root/.pub-cache/hosted/pub.dev/pana-0.22.2/bin/pana.dart:2[49](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/8075870137/job/22154729575?pr=1585#step:6:51):19)\n<asynchronous suspension>\n"}
Error: Pana exited with code 1
```
here's the failed job
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/actions/runs/8075870137/job/22154729575?pr=1585

After some search, https://github.com/actions/runner-images/issues/6775, I tried to add this as a workaround in my step, but it's no luck.
```
git config --global --add safe.directory '/github/workspace'
```

I'm not very sure if it should be added inside the `Dockerfile`, I think it can easily reproduce this issue with the following workflow config
```yaml
jobs:
  flutter_codestyle_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
```
