### ISSUE TITLE
Multiple branch support

### ISSUE THREAD

**Issue by shamblett** [axel-op/dart_package_analyzer#3]
I have the action in my master branch, this works OK if I trigger it from github.

I've added a branches: clause to the action to only run on three branches when pushed but this doesn't seem to be working, when I push one of my branches the action is not trigerred, and if it was would it run on the branch I have pushed or master?

I'm not clear on how to set this up.

**Comment by axel-op** [comment]
I'm not entirely sure I understand what's the issue here.

Everything is explained [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags), you have to edit your workflow file if you want it to be triggered on specific branches. You can use a pattern or you can directly specify the name of the branches you want your jobs to be triggered on.

Examples from the page I linked:
```yml
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
      - 'mona/octocat' # Push events to branches matching refs/heads/mona/octocat
      - 'releases/**'  # Push events to branches matching refs/heads/releases/10
```
If you're talking about your repository [`mqtt_client`](https://github.com/shamblett/mqtt_client/blob/master/.github/workflows/pana.yml) I don't see any problem with your workflow, it will only run on the branches you specified.

Could you detail your issue a bit more?
