### ISSUE TITLE
Using custom Flutter channel (beta, master, dev)

### ISSUE THREAD

**Issue by Dogacel** [axel-op/dart_package_analyzer#5]
I am trying to use dart-package-analyzer in github actions with a beta version of flutter but I am getting the following issue:

#### General
- **Fix dependencies in `pubspec.yaml`**
  Running flutter pub upgrade failed with the following output:
  - ERR: The current Flutter SDK version is 1.12.13+hotfix.9.
  - Because boo_app requires Flutter SDK version ^1.17.0, version solving failed.

and I also get 
- **No valid SDK**
  **20.0 points**
  The analysis could not detect a valid SDK that can use this package.

and this is my workflow file

```yml
jobs:
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: axel-op/dart-package-analyzer@stable
        id: analysis # set an id for the current step
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # You can then use this id to retrieve the outputs in the next steps.
      # The following step shows how to exit the workflow with an error if a score is below 100:
      - name: Check scores
        # NB: "analysis" is the id set above. Replace it with the one you used if different.
        run: |
          MAINTENANCE_SCORE=${{ steps.analysis.outputs.maintenance }}
          HEALTH_SCORE=${{ steps.analysis.outputs.health }}
          if (( $(echo "$MAINTENANCE_SCORE < 50" | bc) )) || (( $(echo "$HEALTH_SCORE < 50" | bc) ))
          then
            echo "Scores are less than 50"
            exit 1
          fi
```

This is not much different from the default version. Can you help me with this?

**Comment by axel-op** [comment]
Hi,

You're right, my action doesn't handle other branches than `stable`.

To do what you want to do, you need to set up your own container with Flutter, and to copy this repository in it. Try this:

```yaml
  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set path
        run: |
          echo "::add-path::$HOME/flutter/bin"
          echo "::add-path::$HOME/flutter/bin/cache/dart-sdk/bin"
          echo "::add-path::$HOME/.pub-cache/bin"

      - name: Install Flutter and Pana
        env:
          # The Flutter channel you want to use
          CHANNEL: beta
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends unzip
          git clone https://github.com/flutter/flutter.git -b $CHANNEL $HOME/flutter
          flutter doctor
          flutter pub global activate pana

      - name: Run Dart Package Analyzer
        env:
          INPUT_GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_MINANNOTATIONLEVEL: info
        run: |
          git clone https://github.com/axel-op/dart-package-analyzer.git -b stable $HOME/dart-package-analyzer
          cd $HOME/dart-package-analyzer/app
          flutter pub get
          dart bin/main.dart

      - name: Check scores
        # ...
```
