### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by dacianf** [axel-op/dart_package_analyzer#9]
Hey @axel-op , I've tried to use this action on a macOS runner and it fails with `##[error]Container action is only supported on Linux`.
Do I make something wrong? Can you make it run on macOS too, I supposed it should work since MacOS is a Unix based OS?
I've tried it with your example:
`
    - uses: axel-op/dart-package-analyzer@v3
      # set an id for the current step
      id: analysis
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        # You can then use this id to retrieve the outputs in the next steps.
        # The following step shows how to exit the workflow with an error if the total score in percentage is below 50:
    - name: Check scores
      env:
        # NB: "analysis" is the id set above. Replace it with the one you used if different.
        TOTAL: ${{ steps.analysis.outputs.total }}
        TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
      run: |
        PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
        if (( $PERCENTAGE < 80 ))
        then
          echo Score too low!
          exit 1
        fi
`

**Comment by axel-op** [comment]
Hi @dacianf, 

This action uses a container to execute. The issue that you have is due to a limitation imposed by GitHub on the execution of containerized actions. As you can see on [this page](https://docs.github.com/en/actions/creating-actions/about-actions#types-of-actions):

```txt
Docker container actions can only execute on runners with a Linux operating system.
```

Also from [this page of the documentation](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idservices):

```txt
If your workflows use Docker container actions or service containers, then you must use a Linux runner:
- If you are using GitHub-hosted runners, you must use the ubuntu-latest runner.
```

Why do you want to run this action on a MacOS machine? The result will be the same using Ubuntu.

Maybe you want to integrate it in a job that contains other steps, but this is a bad idea. As I wrote in the README, you should use a separate job to run this action, because it uses a container with its own version of Dart and Flutter.

**Comment by dacianf** [comment]
> Maybe you want to integrate it in a job that contains other steps, but this is a bad idea. As I wrote in the README, you should use a separate job to run this action, because it uses a container with its own version of Dart and Flutter.

This is exactly what I wanted. I can create a separate job for this action but I run actions on a local machine which is a mac and has osx on it, so I can't do that either, because it is not ubuntu runner.

**Comment by axel-op** [comment]
> This is exactly what I wanted. I can create a separate job for this action but I run actions on a local machine which is a mac and has osx on it, so I can't do that either, because it is not ubuntu runner.

Ok, so, from the same page of documentation:

```txt
If your workflows use Docker container actions or service containers, then you must use a Linux runner:
- [...]
- If you are using self-hosted runners, you must use a Linux machine as your runner and Docker must be installed.
```

So, regarding your main issue, I can't do anything to change that.

Secondly, including this action in a job with other steps will only slow this job down, because this will add the time to retrieve the container image at the beginning, which will only be used by this action. On another hand, if you create a second job just for this action, the two jobs will run in parallel and your first job will complete faster.

Why can't you create another job?

**Comment by axel-op** [comment]
> Why can't you create another job?

Ok so actually your comment already answers this question.

As a workaround, if Dart and Flutter are already installed by yourself on your machine, you can use the implementation I previously described [here](https://github.com/axel-op/dart-package-analyzer/issues/5#issuecomment-620278367) to use this action anyway. Your workflow could be something like that:

```yaml
  your-job:
    runs-on: [self-hosted, ...]
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        # Make sure Flutter is on your path
        run: ...

      - name: Install Pana
        run: flutter pub global activate pana

      # Other steps
      # ...

      - name: Run Dart Package Analyzer
        env:
          # Simulate an input given using the "with" keyword
          INPUT_GITHUBTOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://github.com/axel-op/dart-package-analyzer.git -b v3 $HOME/dart-package-analyzer
          cd $HOME/dart-package-analyzer/app
          flutter pub get
          dart bin/main.dart

      - name: Check scores
        # ...
```

No container needed! And no extra time added at the beginning.
